apiVersion: v1
kind: Service
metadata:
  name: project2-service
  namespace: team-ccc
  labels:
    name: project2-app
spec:
  selector:
    app: project2-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http