version: "3.8"

services:
  project1:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://postgresdb-1.cokq2ji1eim5.us-east-1.rds.amazonaws.com:5432/postgres
      - DB_USERNAME=postgresDB
      - DB_PASSWORD=basketball
    container_name: project1-container
    depends_on:
      - postgres
    volumes:
      - ./logs/applogs.log:/logs/application.log
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=basketball
    container_name: postgres_container
    volumes:
     - db-data:/var/lib/postgresql/data
  promtail:
     image: grafana/promtail:latest
     container_name: promtail_container
     volumes:
      - ./promtail/promtail-docker-config.yml:/etc/promtail/docker-config.yaml
      - ./logs/applogs.log:/var/logs/application.log
     command: "--config.file=/etc/promtail/docker-config.yaml"
  loki:
     image: grafana/loki:latest
     container_name: loki_container
     ports: 
      - 3100:3100
  grafana:
     image: grafana/grafana:latest
     container_name: grafana_container
     volumes:
      - grafana-data:/var/lib/grafana 
     ports: 
      - 3000:3000
     depends_on: 
      - loki
      
  prometheus:
    image: prom/prometheus:latest
    ports:
     - 9090:9090
    volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     - prometheus-data:/prometheus
    container_name: project1-prometheus
    
   
    
   
volumes:
  db-data:
   driver: local
  grafana-data:
   driver: local
  prometheus-data:
   driver: local
  